security:
  jwt:
    secret: AccountKey=iEg0P8rVh5FTRiyQ8Cj9TObElZtTfq6CPikJec7xNvXr8ryLvJrSHlyIKsuHm6mrf3ZyAWq5k1vjLfZmcyRfcQ==;

azure:
  cosmos:
    uri: https://dev-rbox.documents.azure.com:443/
    key: daJZkJHZSTbqsubF12oJ9Z6xK3PSya5R2bADXhkyKremSCjHmi2HNE46pn1Ie9y82SWHF4lV4HbBdLPJdXSW8g==
    database: rbox
otp:
  ttl: 30000
sms:
  sid: AC5e9fe319e2bbe55e1eae001a5b55cc6a
  token: e88338c646f9ed16049d216c434e59d8
  from: +17754028141